### ISSUE TITLE
Bug? - time in `goal-history.json` is always 00:00:00

### ISSUE THREAD

**Issue by danieltomasz** [lynchjames/obsidian-writing-goals#15]
date is correct

**Comment by lynchjames** [comment]
This is by design to store goal history with a resolution of 1 day so that the daily goal is reset at midnight. I could increase this to hourly with some logic to use the latest history item during each day.

This would allow for hourly reporting but could add a lot of data to the json file over time.

**Comment by danieltomasz** [comment]
Maybe there is no need, if this is planned mechanism, I am closing the issue, reopen it if you want it change it
