### ISSUE TITLE
[BUG] Writing goals reaaally wants me to add a writing goal from the context menu

### ISSUE THREAD

**Issue by FeralFlora** [lynchjames/obsidian-writing-goals#37]
I sometimes end up clicking "Add a writing goal" in the context menu by mistake. This is because the hover selector for this button seems extra "sticky", and I have to move the cursor far beyond the button before the highlight actually moves. Due to this, there is a mismatch between the cursor position and the highlight.

![Obsidian_cpS8kZW8Ht](https://github.com/lynchjames/obsidian-writing-goals/assets/33608083/2723af24-21b8-48d0-83eb-5b767d43d76b)

Theme: Prism
Obsidian version: 1.4.13
Writing goals version: 0.9.0

**Comment by lynchjames** [comment]
Thanks. I think this is an Obsidian bug due to the implementation of [custom icons](https://docs.obsidian.md/Plugins/User+interface/Icons#Add+your+own+icon) with a viewbox of `0 0 100 100`. Here is the icon svg highlighted in the inspector:

![image](https://github.com/lynchjames/obsidian-writing-goals/assets/113271/5f056cd8-aa66-4103-8edc-c7a4673987b3)

I'll report this to Obsidian as a bug.

**Comment by lynchjames** [comment]
On further investigation, this is **_not_** an Obsidian bug, this is due to me scaling up the SVG in CSS. I'll look at scaling the dimensions within the SVG to remove the CSS transform.

**Comment by lynchjames** [comment]
Should be fixed in 0.9.1
